fruits = ['mango','orange',150,'pineapple','bannana','grapes',2000]
vegitables = ['tomato','potato','ladies finger','colfowler','brocoli']

fruits.append('chiku')
fruits.append(150)
print(fruits)
fruits.extend(vegitables)
print(fruits)
fruits.insert(0,2000)
print(fruits)
fruits.remove(150)
print(fruits)
temp=fruits.pop(7)
print(fruits)
print(temp)
# vegitables.clear()
print(vegitables)
# del vegitables
# print(vegitables)
temp = fruits.index('tomato')
print(temp)
temp = fruits.count(2000)
print(temp)
# vegitables.sort()
# print(vegitables)
fruits.reverse()
print(fruits)
temp = fruits.copy()
print(temp)